2023-08-15 15:52:35,677 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:52:38,992 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 97, in post
    return JsonResponse(json.dumps(res))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2023-08-15 15:52:51,403 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 15:52:51,852 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:52:53,750 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
2023-08-15 15:53:35,075 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:53:35,555 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:53:39,104 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (2 byte(s) given) parameters.
2023-08-15 15:53:39,104 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (2) byte(s).
2023-08-15 15:53:39,108 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:53:39,108 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:53:39,108 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:53:39,165 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:53:51,235 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:53:51,721 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:53:54,461 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:54:04,351 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:54:04,817 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:54:48,910 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:54:49,533 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:54:51,903 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:54:52,370 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:55:00,574 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (2 byte(s) given) parameters.
2023-08-15 15:55:00,574 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (2) byte(s).
2023-08-15 15:55:00,575 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:55:00,575 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:55:00,575 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:55:00,630 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:55:11,095 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:55:11,690 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:55:25,020 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (2 byte(s) given) parameters.
2023-08-15 15:55:25,020 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (2) byte(s).
2023-08-15 15:55:25,021 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:55:25,021 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:55:25,021 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:55:25,081 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:56:29,550 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:56:30,212 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:56:46,588 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (2 byte(s) given) parameters.
2023-08-15 15:56:46,588 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (2) byte(s).
2023-08-15 15:56:46,588 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:56:46,589 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:56:46,589 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:56:46,648 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:57:01,234 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:57:01,692 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:57:04,379 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (2 byte(s) given) parameters.
2023-08-15 15:57:04,379 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (2) byte(s).
2023-08-15 15:57:04,380 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:57:04,380 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:57:04,380 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:57:04,432 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 15:58:35,864 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/msg_utils/send_msg.py changed, reloading.
2023-08-15 15:58:36,515 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 15:58:42,412 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (1 byte(s) given) parameters.
2023-08-15 15:58:42,412 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (1) byte(s).
2023-08-15 15:58:42,413 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 15:58:42,413 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 15:58:42,414 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 15:58:42,471 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - ERROR    - Internal Server Error: /api/pwd_manage/send_msg/
Traceback (most recent call last):
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/wangzhexian/project/dcmc/apps/pwd_app/views.py", line 98, in post
    return JsonResponse(json.dumps(res))
  File "/Users/wangzhexian/project/dcmc/venv/lib/python3.8/site-packages/django/http/response.py", line 596, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
2023-08-15 16:14:32,366 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:14:33,058 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:17:59,570 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:18:00,154 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:18:06,444 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - override steps (5) and chunk_size (512) as content does not fit (1 byte(s) given) parameters.
2023-08-15 16:18:06,445 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - WARNING  - Trying to detect encoding from a tiny portion of (1) byte(s).
2023-08-15 16:18:06,445 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2023-08-15 16:18:06,446 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii should target any language(s) of ['Latin Based']
2023-08-15 16:18:06,446 - /api/pwd_manage/send_msg/ - 127.0.0.1 - None - INFO     - ascii is most likely the one. Stopping the process.
2023-08-15 16:27:31,500 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:27:32,264 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:35:17,198 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:35:17,815 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:42:19,909 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:42:20,669 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:45:43,213 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:45:43,774 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 16:56:20,339 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 16:56:21,062 - None - None - None - INFO     - Watching for file changes with StatReloader
2023-08-15 17:24:20,887 - None - None - None - INFO     - /Users/wangzhexian/project/dcmc/apps/pwd_app/views.py changed, reloading.
2023-08-15 17:24:21,590 - None - None - None - INFO     - Watching for file changes with StatReloader
